import os
import glob
from PIL import Image

# change these to folders w/ images 
IMAGE_FOLDER = "./imgs/stats"
OUTPUT_FILE = "stats.h"
ARRAY_NAME = "stats"
TARGET_SIZE = (128, 128)

def rgb_to_rgb565(r, g, b):
    color = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    swapped_color = ((color & 0x00FF) << 8) | ((color & 0xFF00) >> 8) # because edianness diff for lcd
    return swapped_color

def generate_c_array():
    search_path = os.path.join(IMAGE_FOLDER, "*.png")
    image_files = sorted(glob.glob(search_path))
    
    if not image_files:
        print(f"Error: No PNG files found in the '{IMAGE_FOLDER}' folder!")
        return

    num_frames = len(image_files)
    pixels_per_frame = TARGET_SIZE[0] * TARGET_SIZE[1]
    
    print(f"Found {num_frames} frames! Converting to {TARGET_SIZE[0]} by {TARGET_SIZE[1]} in RGB565...")

    with open(OUTPUT_FILE, "w") as f:
        f.write("// Auto-generated by Tamagacha Image Converter\n")
        f.write(f"const uint16_t {ARRAY_NAME}[{num_frames}][{pixels_per_frame}] = {{\n")

        for idx, img_path in enumerate(image_files):
            print(f"Processing {img_path}...")
            img = Image.open(img_path).convert("RGB") 
            img = img.resize(TARGET_SIZE) 
            pixels = img.load()
            
            f.write("    { // Frame " + str(idx) + "\n        ")
            
            hex_strings = []
            for y in range(TARGET_SIZE[1]):
                for x in range(TARGET_SIZE[0]):
                    r, g, b = pixels[x, y]
                    color_565 = rgb_to_rgb565(r, g, b)
                    hex_strings.append(f"0x{color_565:04X}")
            
            for i in range(0, len(hex_strings), 8):
                line = ", ".join(hex_strings[i:i+8])
                if i + 8 < len(hex_strings):
                    line += ","
                f.write(line + "\n        ")
            
            if idx < num_frames - 1:
                f.write("\n    },\n")
            else:
                f.write("\n    }\n")

        f.write("};\n")
        
    print(f"\nSuccess! Wrote array to {OUTPUT_FILE}")

generate_c_array()